# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.50.5 docker://sincoser/tektoncd-pipeline-entrypoint:v0.50.5
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/proxy-webhook:v0.68.1 docker://sincoser/tektoncd-operator-proxy-webhook:v0.68.1
        skopeo copy --all docker://gcr.io/tekton-releases/dogfooding/tkn docker://sincoser/tektoncd-tkn:v1.0.0
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.68.1 docker://sincoser/tektoncd-operator-operator:v0.68.1
        skopeo copy --all docker://gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/webhook:v0.68.1 docker://sincoser/tektoncd-operator-webhook:v0.68.1
        

